const clientTypes = {
  GET_CAR: 'GET_CARS',
  AUTH: 'AUTH',
  REGISTER: 'REGISTER',
  CHEK_AUTH: 'CHEK_AUTH',
  SIGNOUT: 'SIGNOUT',
  GETALLCAR: 'GETALLCAR',
  ESSAI_CAR: 'ESSA_CAR',
  RESERVE: 'RESERVE',
  CLIENT_ERROR: 'CLIENT_ERROR',
};

export default clientTypes;
